import { type MigrationInterface, type QueryRunner } from "typeorm";

// this was generated by ai because im not arsed writing 400 manual sql queries

const ListingType = {
  SINGLE: 0,
  DOUBLE: 1,
  FAMILY: 2,
  LUXURY: 3,
} as const;

type ListingTypeValue = (typeof ListingType)[keyof typeof ListingType];

type SeedListing = {
  type: ListingTypeValue;
  price: number;
  available: boolean;
};

type SeedLocation = {
  name: string;
  city: string;
  country: string;
  listings: SeedListing[];
};

const listing = (
  type: ListingTypeValue,
  price: number,
  available = true,
): SeedListing => ({ type, price, available });

const locations: SeedLocation[] = [
  {
    name: "The Harbourview Hotel",
    city: "Sydney",
    country: "Australia",
    listings: [
      listing(ListingType.SINGLE, 120),
      listing(ListingType.DOUBLE, 180),
      listing(ListingType.FAMILY, 260),
      listing(ListingType.LUXURY, 540),
      listing(ListingType.DOUBLE, 175, false),
    ],
  },
  {
    name: "Sakura Ryokan",
    city: "Kyoto",
    country: "Japan",
    listings: [
      listing(ListingType.SINGLE, 95),
      listing(ListingType.SINGLE, 110),
      listing(ListingType.DOUBLE, 190),
      listing(ListingType.LUXURY, 620),
      listing(ListingType.FAMILY, 240, false),
    ],
  },
  {
    name: "Grand Palais Suites",
    city: "Paris",
    country: "France",
    listings: [
      listing(ListingType.SINGLE, 150),
      listing(ListingType.DOUBLE, 230),
      listing(ListingType.FAMILY, 340),
      listing(ListingType.LUXURY, 780),
      listing(ListingType.DOUBLE, 220),
    ],
  },
  {
    name: "Andes Backpackers Lodge",
    city: "Bogota",
    country: "Colombia",
    listings: [
      listing(ListingType.SINGLE, 45),
      listing(ListingType.SINGLE, 55),
      listing(ListingType.DOUBLE, 85),
      listing(ListingType.FAMILY, 130),
      listing(ListingType.DOUBLE, 80, false),
    ],
  },
  {
    name: "Lakeside Retreat",
    city: "Queenstown",
    country: "New Zealand",
    listings: [
      listing(ListingType.SINGLE, 105),
      listing(ListingType.DOUBLE, 165),
      listing(ListingType.FAMILY, 250),
      listing(ListingType.LUXURY, 590),
      listing(ListingType.SINGLE, 100),
    ],
  },
  {
    name: "Al Fahidi Heritage Inn",
    city: "Dubai",
    country: "United Arab Emirates",
    listings: [
      listing(ListingType.SINGLE, 130),
      listing(ListingType.DOUBLE, 210),
      listing(ListingType.FAMILY, 320),
      listing(ListingType.LUXURY, 950),
      listing(ListingType.DOUBLE, 205, false),
    ],
  },
  {
    name: "Cedar & Pine Hostel",
    city: "Vancouver",
    country: "Canada",
    listings: [
      listing(ListingType.SINGLE, 70),
      listing(ListingType.SINGLE, 75),
      listing(ListingType.DOUBLE, 140),
      listing(ListingType.FAMILY, 210),
      listing(ListingType.DOUBLE, 135),
    ],
  },
  {
    name: "Villa Trastevere",
    city: "Rome",
    country: "Italy",
    listings: [
      listing(ListingType.SINGLE, 115),
      listing(ListingType.DOUBLE, 175),
      listing(ListingType.FAMILY, 265),
      listing(ListingType.LUXURY, 660),
      listing(ListingType.SINGLE, 110, false),
    ],
  },
  {
    name: "Karoo Sky Lodge",
    city: "Cape Town",
    country: "South Africa",
    listings: [
      listing(ListingType.SINGLE, 60),
      listing(ListingType.DOUBLE, 95),
      listing(ListingType.FAMILY, 150),
      listing(ListingType.LUXURY, 410),
      listing(ListingType.DOUBLE, 90),
    ],
  },
  {
    name: "Rajasthan Haveli House",
    city: "Jaipur",
    country: "India",
    listings: [
      listing(ListingType.SINGLE, 40),
      listing(ListingType.SINGLE, 50),
      listing(ListingType.DOUBLE, 75),
      listing(ListingType.FAMILY, 120),
      listing(ListingType.LUXURY, 330, false),
    ],
  },
];

export class SeedDb1791459930115 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const location of locations) {
      const inserted = (await queryRunner.query(
        `INSERT INTO "location" ("name", "city", "country")
         VALUES ($1, $2, $3)
         RETURNING "id"`,
        [location.name, location.city, location.country],
      )) as { id: string }[];

      const locationId = inserted[0].id;

      for (const item of location.listings) {
        await queryRunner.query(
          `INSERT INTO "listing" ("type", "price", "available", "locationId")
           VALUES ($1, $2, $3, $4)`,
          [String(item.type), item.price, item.available, locationId],
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const names = locations.map((location) => location.name);

    await queryRunner.query(
      `DELETE FROM "listing"
       WHERE "locationId" IN (
         SELECT "id" FROM "location" WHERE "name" = ANY($1)
       )`,
      [names],
    );

    await queryRunner.query(`DELETE FROM "location" WHERE "name" = ANY($1)`, [
      names,
    ]);
  }
}
